---
- name: "Set a Fact from Dictionary Values"
  hosts: all
  collections:
  - theforeman.foreman
  vars:
    my_dc: DC1
    compute_resources:
      DC1: virtualization-manager-1.example.com
      DC2: virtualization-manager-2.example.com
    lifecycle_envs:
      Prod: Production
      UAT: User_Acceptance_Test
      Dev: Development
    content_views:
      RHEL7: "Red Hat Enterprise Linux 7"
      RHEL8: "Red Hat Enterprise Linux 8"
    kickstart_repos:
      RHEL_7_7: "Red Hat Enterprise Linux 7 Server Kickstart x86_64 7.7"
      RHEL_7_8: "Red Hat Enterprise Linux 7 Server Kickstart x86_64 7.8"
      RHEL_8_0: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.0"
    subnets:
      App1_subnet: "192.168.100.0/24"
      App2_subnet: "10.1.0.0/16"
      DMZ: "172.16.0.0/22"

  tasks:
  - name: "Lookup the Virtualization Manager for the DC"
    set_fact:
      compute_resource: "{{ item.value }}"
    loop: "{{ lookup('dict', compute_resources) }}"
    when: "'{{ my_dc }}' in item.key"

  - name: "Print the fact"
    debug:
      msg: "{{ compute_resource }}"
