---
- name: "Set a Fact from Dictionary Values"
  hosts: all
  collections:
  - theforeman.foreman
  vars:
    my_dc: DC1
    compute_resources:
      DC1: virtualization-manager-1.example.com
      DC2: virtualization-manager-2.example.com
    lifecycle_envs:
      Prod: Production
      UAT: User_Acceptance_Test
      Dev: Development
    content_views:
      RHEL7: "Red Hat Enterprise Linux 7"
      RHEL8: "Red Hat Enterprise Linux 8"
    kickstart_repos:
      RHEL7_7: "Red Hat Enterprise Linux 7 Server Kickstart x86_64 7.7"
      RHEL7_8: "Red Hat Enterprise Linux 7 Server Kickstart x86_64 7.8"
      RHEL8_0: "Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.0"
    subnets:
      app1_subnet: "192.168.100.0/24"
      app2_subnet: "10.1.0.0/16"
      dmz: "172.16.0.0/22"

  tasks:
  - name: "Lookup the Virtualization Manager for the DC"
    set_fact:
      compute_resource: "{{ item.value }}"
    loop: "{{ lookup('dict', compute_resources) }}"
    when: "'{{ my_dc }}' in item.key"


  - name: "Lookup Content View"
    set_fact:
      content_view: "{{ item.value }}"
    loop: "{{ lookup('dict', content_views) }}"
    when: "'{{ os_version.split("_")[0] }}' in item.key"

  - name: "Lookup Kickstart Repo"
    set_fact:
      content_view: "{{ item.value }}"
    loop: "{{ lookup('dict', kickstart_repos) }}"
    when: "'{{ os_version }}' in item.key"

  - name: "Lookup Content View"
    set_fact:
      content_view: "{{ item.value }}"
    loop: "{{ lookup('dict', content_views) }}"
    when: "'{{ os_version.split("_")[0] }}' in item.key"