---
- name: "Create a host"
  hosts: all
  collections:
   - theforeman.foreman
  tasks:

  - name: "Create a host"
    foreman_host:
      username: "{{ satellite_user }}"
      password: "{{ satellite_pw }}"
      server_url: "https://satellite.example.com"
      name: "{{ requested_server_name }}"
      compute_resource: "{{ compute_resource }}"
      architecture: "x86_64"
      build: true
      domain: "{{ example.com }}"
      compute_profile: "{{ compute_profile }}"
      organization: "{{ satellite_org }}"
      location: "{{ satellite_location }}"
      mac: "{{ 56 | random_mac }}"
      ip: "{{ server_ip }}"
      root_pass: "{{ new-servers-root-pw }}"
      subnet: "{{ subnet }}"
      provision_method: "build"
      lifecycle_environment: "{{ lifecycle_env }}"
      content_view: "{{ content_view }}"
      operatingsystem: "{{ operating_system }}"
      ptable: "Kickstart default"
      content_source: "satellite.example.com"
      pxe_loader: "PXELinux BIOS"
      kickstart_repository: "{{ kickstart_repo }}"
      validate_certs: no
      parameters:
        - name: subscription_manager
          value: yes
        - name: subscription_manager_certpkg_url
          value: https://satellite.labgear.io/pub/katello-ca-consumer-latest.noarch.rpm
        - name: redhat_install_host_tools
          value: yes
        - name: redhat_install_agent
          value: yes
        - name: subscription_manager_org
          value: "{{ satellite_org }}"
        - name: activation_key
          value: RHEL-8-Prod
        - name: http-proxy
          value: squid.labgear.io
        - name: http-proxy-port
          value: 3128
        - name: http-proxy-user 
          value: sat_squid_user
        - name: http-proxy-password
          value: OWRmNzE4N2RkYzdkYzkyZWE2NTc3YWRj
        - name: foo
          value: yes
      state: present